### ISSUE TITLE
Term.alert is missing

### ISSUE THREAD

**Issue by ExtReMLapin** [slaughter/GMod-Terminal#1]
It's missing

**Comment by slaughter** [comment]
[line 35](https://github.com/fghdx/GMod-Terminal/blob/master/lua/autorun/terminal.lua#L35)

What do you mean by missing?

**Comment by ExtReMLapin** [comment]
Oops, my bad, i mean, Term.error

**Comment by slaughter** [comment]
Ops. That is meant to be Term.alert... :>

**Comment by slaughter** [comment]
Thanks for pointing that out.
